parameters:

services:
  # Configuration par défaut pour les services dans ce fichier
  _defaults:
    autowire: true      # Injection automatique des dépendances
    autoconfigure: true # Enregistre automatiquement comme handler
  # Autres services dans le répertoire src/
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
